sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jonthornton07/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jonthornton07/react-test npm test

after_success:
    - docker build -t jonthornton07/multi-client ./client
    - docker build -t jonthornton07/multi-nginx ./nginx
    - docker build -t jonthornton07/multi-server ./server
    - docker build -t jonthornton07/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push jonthornton07/multi-client
    - docker push jonthornton07/multi-nginx
    - docker push jonthornton07/multi-server
    - docker push jonthornton07/multi-worker