sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jonthornton07/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jonthornton07/react-test npm run test
